#!/usr/bin/env -S deno run --allow-read --allow-write



/**
 * Hex Dice Portable Game Notation (HDPGN) Generator
 *
 * This script loads a JSON replay file (generated by the Hex Dice game simulator)
 * and converts it into a HDPGN format, inspired by Chess PGN.
 *
 * Usage:
 *   deno run --allow-read --allow-write generate_hdpgn.ts <replay_file.json> [output_file.hdpgn]
 */

// --- Global Constants from game.js (replicated for standalone script) ---
// In a real project, these might be imported or shared differently.
// For simplicity and standalone execution, replicating necessary parts.
// const UNIT_STATS = {
//     1: { name: "Fencer", attack: 2, armor: 2, range: 0, distance: 2, movement: '*' },
//     2: { name: "Archer", attack: 2, armor: 1, range: 2, distance: 1, movement: '*' },
//     3: { name: "Hussar", attack: 3, armor: 0, range: 0, distance: 3, movement: 'L' },
//     4: { name: "Knight", attack: 2, armor: 1, range: 0, distance: 3, movement: 'X' },
//     5: { name: "Tanker", attack: 1, armor: 4, range: 0, distance: 1, movement: '*' },
//     6: { name: "Oracle", attack: 0, armor: 0, range: 2, distance: 1, movement: '*' },
// };

// Simplified hex grid generation to get q,r from hexId
// This needs to match the logic in game.js generateHexGrid
function generateMinimalHexGrid(radius: number) {
    const hexes = [];
    const hexesQR = {}; // q*1000 + r -> id

    let id = 0;
    for (let q = -radius; q <= radius; q++) {
        for (let r = -radius; r <= radius; r++) {
            if (-q - r < -radius || -q - r > radius) continue; // Check s coordinate

            hexes.push({ id, q, r, s: -q-r });
            hexesQR[(q * 1e3) + r] = id;
            id++;
        }
    }
    return { hexes, hexesQR };
}

interface MinimalHexGrid {
    hexes: {id: number, q: number, r: number, s: number}[];
    hexesQR: { [key: string]: number };
}

function getHexQR(hexId: number, hexGrid: MinimalHexGrid) {
    const hex = hexGrid.hexes[hexId];
    return hex ? { q: hex.q, r: hex.r } : null;
}
// --- End Global Constants ---


interface MoveRecord {
    turn: number;
    player: number;
    aiType?: string;
    actionType: string; // 'deploy', 'move', 'attack', 'reroll', 'guard', 'merge', 'spellcast', etc.
    fromHex?: number;
    toHex?: number;
    unitValue?: number;
    logMessage?: string;
    stateHash?: string; // Base64 encoded JSON string of game state
}

interface GameReplay {
    gameNumber: number;
    winner: number;
    winnerReason: string;
    totalTurns: number;
    moves: MoveRecord[];
    // ... other properties
}

interface ReplayData {
    metadata: {
        date: string;
        games: number;
        aiTypes: string[];
        version: string;
    };
    games: GameReplay[];
    summary: unknown; // Not strictly needed for HDPGN generation
}

interface GameStateSnapshot { // More precise type for decoded stateHash
    playersDice: string;
    currentPlayerIndex: number;
    phase: string;
    turnCount: number;
    hexes: {q: number, r: number}[]; // Assuming only q,r are relevant for radius estimation
    // Add other relevant properties if they exist in stateHash
}

// Function to convert game state (from stateHash) to HDFEN
//
// IMPORTANT LIMITATION: The `stateHash` field in existing replay JSON files (generated by `replay.ts`)
// only stores a simplified view of the game state, primarily `playersDice:val-hex-death|...`.
// It does NOT contain dynamic unit flags like `hasMovedOrAttackedThisTurn`, `isGuarding`, `skirmishBuff`.
// Therefore, the HDFEN generated by this script will use placeholders for these flags.
// To get a truly "Detailed HDFEN" with these flags, the `stateHash` generation in `replay.ts`
// would need to be modified to store more comprehensive unit state.
function convertStateToHDFEN(gameState: GameStateSnapshot, hexGrid: MinimalHexGrid) {
    // Reconstruct piece placement from gameState.playersDice
    const piecePlacementTokens: string[] = [];
    let emptyCount = 0;

    // gameState.playersDice format: p0Dice:val-hex-death|val-hex-death;p1Dice:...
    const playersDiceStr = gameState.playersDice;
    const playerUnits: { [hexId: number]: { playerId: number, value: number, isDeath: boolean } } = {};

    playersDiceStr.split(';').forEach(playerStr => {
        if (!playerStr) return;
        const [playerKey, diceData] = playerStr.split(':');
        const playerId = parseInt(playerKey.replace('p', '').replace('Dice', ''));

        diceData.split('|').forEach(unitStr => {
            if (!unitStr) return;
            const [valueStr, hexIdStr, deathStr] = unitStr.split('-');
            const value = parseInt(valueStr);
            const hexId = parseInt(hexIdStr);
            const isDeath = deathStr === 'true';

            if (!isDeath && !isNaN(hexId)) {
                playerUnits[hexId] = { playerId, value, isDeath };
            }
        });
    });

    // Assume hexGrid.hexes is canonically ordered by id
    for (let i = 0; i < hexGrid.hexes.length; i++) {
        const hex = hexGrid.hexes[i];
        const unitOnHex = playerUnits[hex.id];

        if (unitOnHex) {
            if (emptyCount > 0) {
                piecePlacementTokens.push(emptyCount.toString());
                emptyCount = 0;
            }
            // For HDFEN, we need actual unit flags. The `stateHash` in `replay.ts` is simplified.
            // `isMoved` and `isGuarding` are NOT available in the current replay stateHash.
            // `skirmishBuff` is also not available directly in replay stateHash.
            // We will use placeholders for flags that are not stored, and only use `isDeath` which is available.
            const playerID = unitOnHex.playerId;
            const unitValue = unitOnHex.value;
            // Placeholders for unavailable flags:
            const isMoved = '_'; // Not available in replay stateHash
            const isGuarding = '_'; // Not available in replay stateHash
            const isDeath = unitOnHex.isDeath ? 'D' : 'd'; // isDeath IS available
            const skirmishBuff = '0'; // Not available, using default '0'

            piecePlacementTokens.push(`${playerID}${unitValue}${isMoved}${isGuarding}${isDeath}${skirmishBuff}`);
        } else {
            emptyCount++;
        }
    }
    if (emptyCount > 0) {
        piecePlacementTokens.push(emptyCount.toString());
    }
    const piecePlacement = piecePlacementTokens.join('/');

    // Active Player
    const activePlayer = gameState.currentPlayerIndex; // Assuming it's in the decoded state

    // Game Phase (Assuming it's in the decoded state)
    let gamePhase = '';
    switch (gameState.phase) {
        case 'SETUP_ROLL': gamePhase = 'SR'; break;
        case 'SETUP_REROLL': gamePhase = 'SRR'; break;
        case 'SETUP_DEPLOY': gamePhase = 'SD'; break;
        case 'PLAYER_TURN': gamePhase = 'PT'; break;
        case 'GAME_OVER': gamePhase = 'GO'; break;
        default: gamePhase = '__'; break;
    }

    // Turn Number
    const turnNumber = gameState.turnCount; // Assuming it's in the decoded state

    // Other Flags (Assumptions, as rules/options are not in stateHash)
    // This is a major limitation: rules and options are not part of stateHash in replay.ts
    // For now, we will use default/placeholder values.
    const noRerollFlag = '_'; // Cannot determine from stateHash
    const annihilationModeFlag = '_'; // Cannot determine from stateHash
    const mergeModeFlag = '_'; // Cannot determine from stateHash
    const otherFlags = `${noRerollFlag}${annihilationModeFlag}${mergeModeFlag}`;


    return `${piecePlacement} ${activePlayer} ${gamePhase} ${turnNumber} ${otherFlags}`;
}


async function generateHDPGN(replayFile: string, outputFile?: string) {
    const replayData: ReplayData = JSON.parse(await Deno.readTextFile(replayFile));
    let hdpgnContent = '';

    const initialHexGrid = generateMinimalHexGrid(replayData.games[0]?.moves[0]?.stateHash ? 5 : 5); // Default R=5, adjust if possible

    for (const game of replayData.games) {
        // PGN Headers
        hdpgnContent += `[Event "HexDice Game ${game.gameNumber}"]
`;
        hdpgnContent += `[Site "Simulator"]
`;
        hdpgnContent += `[Date "${replayData.metadata.date}"]
`;
        hdpgnContent += `[Round "${game.gameNumber}"]
`;
        hdpgnContent += `[White "Player 0"]
`; // Assuming player 0 is always "White"
        hdpgnContent += `[Black "Player 1"]
`; // Assuming player 1 is always "Black"
        hdpgnContent += `[Result "${game.winner === 0 ? '1-0' : game.winner === 1 ? '0-1' : '1/2-1/2'}"]
`;

        // AI types
        const p0AIType = replayData.metadata.aiTypes[0] || "Human";
        const p1AIType = replayData.metadata.aiTypes[1] || "Human";
        hdpgnContent += `[AIDice "P0=${p0AIType},P1=${p1AIType}"]
`;

        // Initial HDFEN
        if (game.moves.length > 0 && game.moves[0].stateHash) {
            const decodedState = JSON.parse(atob(game.moves[0].stateHash));
            // Dynamically determine radius from initial state for hex grid generation
            const radius = decodedState.hexes[decodedState.hexes.length - 1].q; // Crude way to get radius, needs refinement
            const hexGrid = generateMinimalHexGrid(radius);

            const initialHDFEN = convertStateToHDFEN(decodedState, hexGrid);
            hdpgnContent += `[HDFEN "${initialHDFEN}"]
`;
        }

        hdpgnContent += '\n'; // Empty line after headers

        // Move Text
        let currentTurn = 0;
        let moveText = '';
        for (const move of game.moves) {
            if (move.turn > currentTurn) {
                if (moveText !== '') {
                    hdpgnContent += `${currentTurn}. ${moveText.trim()}
`;
                }
                currentTurn = move.turn;
                moveText = '';
            }

            const fromQR = move.fromHex !== undefined ? getHexQR(move.fromHex, initialHexGrid) : null;
            const toQR = move.toHex !== undefined ? getHexQR(move.toHex, initialHexGrid) : null;

            // Simplified move notation
            let moveStr = `${move.player}${move.unitValue || ''}`;
            switch (move.actionType) {
                case 'deploy':
                    moveStr += `D${toQR ? `(${toQR.q},${toQR.r})` : ''}`;
                    break;
                case 'move':
                    moveStr += `M${fromQR ? `(${fromQR.q},${fromQR.r})` : ''}-${toQR ? `(${toQR.q},${toQR.r})` : ''}`;
                    break;
                case 'attack': // Assuming melee attack
                    moveStr += `A${fromQR ? `(${fromQR.q},${fromQR.r})` : ''}-${toQR ? `(${toQR.q},${toQR.r})` : ''}`;
                    break;
                case 'ranged_attack':
                    moveStr += `RA${fromQR ? `(${fromQR.q},${fromQR.r})` : ''}T${toQR ? `(${toQR.q},${toQR.r})` : ''}`;
                    break;
                case 'special_attack': // Oracle spell or Brave Charge
                    moveStr += `SA${fromQR ? `(${fromQR.q},${fromQR.r})` : ''}T${toQR ? `(${toQR.q},${toQR.r})` : ''}`;
                    break;
                case 'merge':
                    moveStr += `Me${fromQR ? `(${fromQR.q},${fromQR.r})` : ''}-${toQR ? `(${toQR.q},${toQR.r})` : ''}`;
                    break;
                case 'reroll':
                    moveStr += `Reroll(${move.unitValue})`;
                    break;
                case 'guard':
                    moveStr += `Guard(${fromQR ? `(${fromQR.q},${fromQR.r})` : ''})`;
                    break;
                // Add more action types as needed
                default:
                    moveStr += `(${move.actionType})`;
                    break;
            }
            moveText += `${moveStr} `;
        }
        if (moveText !== '') {
            hdpgnContent += `${currentTurn}. ${moveText.trim()}
`;
        }
        hdpgnContent += '\n'; // Separate games with a newline
    }

    if (outputFile) {
        await Deno.writeTextFile(outputFile, hdpgnContent);
        console.log(`HDPGN generated and saved to ${outputFile}`);
    } else {
        console.log(hdpgnContent);
    }
}

if (import.meta.main) {
    const replayFile = Deno.args[0];
    const outputFile = Deno.args[1];

    if (!replayFile) {
        console.error("Usage: deno run --allow-read --allow-write generate_hdpgn.ts <replay_file.json> [output_file.hdpgn]");
        Deno.exit(1);
    }

    generateHDPGN(replayFile, outputFile);
}