#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Hex Dice Portable Game Notation (HDPGN) Generator
 *
 * This script loads a JSON replay file (generated by the Hex Dice game simulator)
 * and converts it into a HDPGN format, inspired by Chess PGN.
 *
 * Usage:
 *   deno run --allow-read --allow-write generate_hdpgn.ts <replay_file.json> [output_file.hdpgn]
 */

// Stub browser APIs for headless execution
function stubBrowserAPIs() {
	const locationStub = {
		search: `?mode=headless`,
		href: `https://hexdice.local/`,
		toString: () => `https://hexdice.local/`
	};
	const documentStub = { getElementById: () => null };
	(globalThis as any).$nextTick = (fn: any) => { try { fn(); } catch(e) { } };
	return { location: locationStub, document: documentStub };
}

// Load game engine
async function loadGameEngine(): Promise<any> {
    const { location: locationStub, document: documentStub } = stubBrowserAPIs();
    const gameCode = await Deno.readTextFile("./game.js");
    const fullCode = `
        ${gameCode}
        return {
            createGame: alpineHexDiceTacticGame,
        };
    `;
	const createModule = new Function('location', 'document', fullCode);
	return createModule(locationStub, documentStub);
}

function getHexQR(hexId: number, game: any) {
    const hex = game.hexes[hexId];
    return hex ? { q: hex.q, r: hex.r } : null;
}

interface MoveRecord {
    turn: number;
    player: number;
    aiType?: string;
    actionType: string;
    fromHex?: number;
    toHex?: number;
    unitValue?: number;
    logMessage?: string;
    stateHash?: string;
}

interface GameReplay {
    gameNumber: number;
    winner: number | -1;
    winnerReason: string;
    totalTurns: number;
    moves: MoveRecord[];
}

interface ReplayData {
    metadata: {
        date: string;
        games: number;
        aiTypes: string[];
        version: string;
    };
    games: GameReplay[];
}

async function generateHDPGN(replayFile: string, outputFile?: string) {
    const replayData: ReplayData = JSON.parse(await Deno.readTextFile(replayFile));
    const engine = await loadGameEngine();
    const game = engine.createGame();
    
    // Initialize hex grid (Standard R=5)
    game.generateHexGrid(5);
    
    let hdpgnContent = '';

    for (const gameInstance of replayData.games) {
        hdpgnContent += `[Event "HexDice Game ${gameInstance.gameNumber}"]\n`;
        hdpgnContent += `[Site "Simulator"]\n`;
        hdpgnContent += `[Date "${replayData.metadata.date}"]\n`;
        hdpgnContent += `[Round "${gameInstance.gameNumber}"]\n`;
        hdpgnContent += `[White "Player 0"]\n`;
        hdpgnContent += `[Black "Player 1"]\n`;
        hdpgnContent += `[Result "${gameInstance.winner === 0 ? '1-0' : gameInstance.winner === 1 ? '0-1' : '1/2-1/2'}"]\n`;

        const p0AIType = replayData.metadata.aiTypes[0] || "Human";
        const p1AIType = replayData.metadata.aiTypes[1] || "Human";
        hdpgnContent += `[AIDice "P0=${p0AIType},P1=${p1AIType}"]\n`;

        if (gameInstance.moves.length > 0 && gameInstance.moves[0].stateHash) {
            const decodedState = JSON.parse(atob(gameInstance.moves[0].stateHash));
            // Use consolidated HDFEN generation from the engine
            const initialHDFEN = game.generateHDFEN(decodedState);
            hdpgnContent += `[HDFEN "${initialHDFEN}"]\n`;
        }

        hdpgnContent += '\n';

        let currentTurn = 0;
        let moveText = '';
        for (const move of gameInstance.moves) {
            if (move.turn > currentTurn) {
                if (moveText !== '') {
                    hdpgnContent += `${currentTurn}. ${moveText.trim()}\n`;
                }
                currentTurn = move.turn;
                moveText = '';
            }

            const fromQR = move.fromHex !== undefined ? game.getHexQR(move.fromHex) : null;
            const toQR = move.toHex !== undefined ? game.getHexQR(move.toHex) : null;

            let moveStr = `${move.player}${move.unitValue || ''}`;
            switch (move.actionType) {
                case 'deploy':
                case 'DEPLOY':
                    moveStr += `D(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'move':
                case 'MOVE':
                    moveStr += `M(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})-(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'attack':
                case 'MELEE':
                case 'combat':
                    if (fromQR && toQR) {
                        moveStr += `A(${fromQR.q},${fromQR.r})-(${toQR.q},${toQR.r})`;
                    } else if (fromQR) {
                        moveStr += `RA(${fromQR.q},${fromQR.r})`;
                    } else {
                        moveStr += `(combat)`;
                    }
                    break;
                case 'ranged_attack':
                case 'RANGED_ATTACK':
                    moveStr += `RA(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})T(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'special_attack':
                case 'SPECIAL_ATTACK':
                case 'COMMAND_CONQUER':
                    moveStr += `SA(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})T(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'merge':
                case 'MERGE':
                    moveStr += `Me(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})-(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'reroll':
                case 'REROLL':
                    moveStr += `Reroll(${move.unitValue})`;
                    break;
                case 'guard':
                case 'GUARD':
                    moveStr += `Guard(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})`;
                    break;
                default:
                    moveStr += `(${move.actionType})`;
                    break;
            }
            moveText += `${moveStr} `;
        }
        if (moveText !== '') {
            hdpgnContent += `${currentTurn}. ${moveText.trim()}\n`;
        }
        hdpgnContent += '\n';
    }

    if (outputFile) {
        await Deno.writeTextFile(outputFile, hdpgnContent);
        console.log(`HDPGN generated and saved to ${outputFile}`);
    } else {
        console.log(hdpgnContent);
    }
}

if (import.meta.main) {
    const replayFile = Deno.args[0];
    const outputFile = Deno.args[1];

    if (!replayFile) {
        console.error("Usage: deno run --allow-read --allow-write generate_hdpgn.ts <replay_file.json> [output_file.hdpgn]");
        Deno.exit(1);
    }

    generateHDPGN(replayFile, outputFile);
}
