#!/usr/bin/env -S deno run --allow-read --allow-write

/**
 * Hex Dice Portable Game Notation (HDPGN) Generator
 *
 * This script loads a JSON replay file (generated by the Hex Dice game simulator)
 * and converts it into a HDPGN format, inspired by Chess PGN.
 *
 * Usage:
 *   deno run --allow-read --allow-write generate_hdpgn.ts <replay_file.json> [output_file.hdpgn]
 */

// Simplified hex grid generation to get q,r from hexId
function generateMinimalHexGrid(radius: number) {
    const hexes = [];
    const hexesQR: { [key: number]: number } = {}; // q*1000 + r -> id

    let id = 0;
    for (let q = -radius; q <= radius; q++) {
        for (let r = -radius; r <= radius; r++) {
            if (-q - r < -radius || -q - r > radius) continue; // Check s coordinate

            hexes.push({ id, q, r, s: -q-r });
            hexesQR[(q * 1e3) + r] = id;
            id++;
        }
    }
    return { hexes, hexesQR };
}

interface MinimalHexGrid {
    hexes: {id: number, q: number, r: number, s: number}[];
    hexesQR: { [key: number]: number };
}

function getHexQR(hexId: number, hexGrid: MinimalHexGrid) {
    const hex = hexGrid.hexes[hexId];
    return hex ? { q: hex.q, r: hex.r } : null;
}

interface MoveRecord {
    turn: number;
    player: number;
    aiType?: string;
    actionType: string;
    fromHex?: number;
    toHex?: number;
    unitValue?: number;
    logMessage?: string;
    stateHash?: string;
}

interface GameReplay {
    gameNumber: number;
    winner: number | -1;
    winnerReason: string;
    totalTurns: number;
    moves: MoveRecord[];
}

interface ReplayData {
    metadata: {
        date: string;
        games: number;
        aiTypes: string[];
        version: string;
    };
    games: GameReplay[];
}

function convertStateToHDFEN(gameState: any, hexGrid: MinimalHexGrid) {
    const piecePlacementTokens: string[] = [];
    let emptyCount = 0;

    const playersDiceStr = gameState.playersDice || "";
    const playerUnits: { [hexId: number]: any } = {};

    playersDiceStr.split(';').forEach((playerStr: string) => {
        if (!playerStr) return;
        const [playerKey, diceData] = playerStr.split(':');
        const playerId = parseInt(playerKey.replace('p', '').replace('Dice', ''));

        if (diceData) {
            diceData.split('|').forEach((unitStr: string) => {
                if (!unitStr) return;
                const parts = unitStr.split('-');
                const value = parseInt(parts[0]);
                const hexId = parseInt(parts[1]);
                const isDeath = parts[2] === 'true' || parts[2] === '1';
                
                // New flags (handle cases where they might be missing in older replays)
                const hasMoved = parts[3] === '1';
                const isGuarding = parts[4] === '1';
                const skirmishBuff = parseInt(parts[5]) || 0;

                if (!isDeath && !isNaN(hexId)) {
                    playerUnits[hexId] = { playerId, value, isDeath, hasMoved, isGuarding, skirmishBuff };
                }
            });
        }
    });

    for (let i = 0; i < hexGrid.hexes.length; i++) {
        const hex = hexGrid.hexes[i];
        const unitOnHex = playerUnits[hex.id];

        if (unitOnHex) {
            if (emptyCount > 0) {
                piecePlacementTokens.push(emptyCount.toString());
                emptyCount = 0;
            }
            const playerID = unitOnHex.playerId;
            const unitValue = unitOnHex.value;
            const isMoved = unitOnHex.hasMoved ? 'M' : 'm';
            const isGuarding = unitOnHex.isGuarding ? 'G' : 'g';
            const isDeath = unitOnHex.isDeath ? 'D' : 'd';
            const skirmishBuff = unitOnHex.skirmishBuff.toString().substring(0, 1);

            piecePlacementTokens.push(`${playerID}${unitValue}${isMoved}${isGuarding}${isDeath}${skirmishBuff}`);
        } else {
            emptyCount++;
        }
    }
    if (emptyCount > 0) {
        piecePlacementTokens.push(emptyCount.toString());
    }
    const piecePlacement = piecePlacementTokens.join('/');

    const activePlayer = gameState.currentPlayerIndex ?? gameState.turn ?? 0;
    let gamePhase = '';
    switch (gameState.phase) {
        case 'SETUP_ROLL': gamePhase = 'SR'; break;
        case 'SETUP_REROLL': gamePhase = 'SRR'; break;
        case 'SETUP_DEPLOY': gamePhase = 'SD'; break;
        case 'PLAYER_TURN': gamePhase = 'PT'; break;
        case 'GAME_OVER': gamePhase = 'GO'; break;
        default: gamePhase = '__'; break;
    }

    const turnNumber = gameState.turnCount ?? 0;
    const noRerollFlag = gameState.noReroll ? 'r' : '_';
    const annihilationModeFlag = (gameState.options || '').includes('a') ? 'a' : '_';
    const mergeModeFlag = (gameState.options || '').includes('m') ? 'm' : '_';
    const otherFlags = `${noRerollFlag}${annihilationModeFlag}${mergeModeFlag}`;

    return `${piecePlacement} ${activePlayer} ${gamePhase} ${turnNumber} ${otherFlags}`;
}

async function generateHDPGN(replayFile: string, outputFile?: string) {
    const replayData: ReplayData = JSON.parse(await Deno.readTextFile(replayFile));
    let hdpgnContent = '';

    const hexGrid = generateMinimalHexGrid(5); // Default R=5 for now

    for (const game of replayData.games) {
        hdpgnContent += `[Event "HexDice Game ${game.gameNumber}"]\n`;
        hdpgnContent += `[Site "Simulator"]\n`;
        hdpgnContent += `[Date "${replayData.metadata.date}"]\n`;
        hdpgnContent += `[Round "${game.gameNumber}"]\n`;
        hdpgnContent += `[White "Player 0"]\n`;
        hdpgnContent += `[Black "Player 1"]\n`;
        hdpgnContent += `[Result "${game.winner === 0 ? '1-0' : game.winner === 1 ? '0-1' : '1/2-1/2'}"]\n`;

        const p0AIType = replayData.metadata.aiTypes[0] || "Human";
        const p1AIType = replayData.metadata.aiTypes[1] || "Human";
        hdpgnContent += `[AIDice "P0=${p0AIType},P1=${p1AIType}"]\n`;

        if (game.moves.length > 0 && game.moves[0].stateHash) {
            const decodedState = JSON.parse(atob(game.moves[0].stateHash));
            const initialHDFEN = convertStateToHDFEN(decodedState, hexGrid);
            hdpgnContent += `[HDFEN "${initialHDFEN}"]\n`;
        }

        hdpgnContent += '\n';

        let currentTurn = 0;
        let moveText = '';
        for (const move of game.moves) {
            if (move.turn > currentTurn) {
                if (moveText !== '') {
                    hdpgnContent += `${currentTurn}. ${moveText.trim()}\n`;
                }
                currentTurn = move.turn;
                moveText = '';
            }

            const fromQR = move.fromHex !== undefined ? getHexQR(move.fromHex, hexGrid) : null;
            const toQR = move.toHex !== undefined ? getHexQR(move.toHex, hexGrid) : null;

            let moveStr = `${move.player}${move.unitValue || ''}`;
            switch (move.actionType) {
                case 'deploy':
                case 'DEPLOY':
                    moveStr += `D(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'move':
                case 'MOVE':
                    moveStr += `M(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})-(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'attack':
                case 'MELEE':
                    moveStr += `A(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})-(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'ranged_attack':
                case 'RANGED_ATTACK':
                    moveStr += `RA(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})T(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'special_attack':
                case 'SPECIAL_ATTACK':
                case 'COMMAND_CONQUER':
                    moveStr += `SA(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})T(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'merge':
                case 'MERGE':
                    moveStr += `Me(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})-(${toQR ? `${toQR.q},${toQR.r}` : ''})`;
                    break;
                case 'reroll':
                case 'REROLL':
                    moveStr += `Reroll(${move.unitValue})`;
                    break;
                case 'guard':
                case 'GUARD':
                    moveStr += `Guard(${fromQR ? `${fromQR.q},${fromQR.r}` : ''})`;
                    break;
                default:
                    moveStr += `(${move.actionType})`;
                    break;
            }
            moveText += `${moveStr} `;
        }
        if (moveText !== '') {
            hdpgnContent += `${currentTurn}. ${moveText.trim()}\n`;
        }
        hdpgnContent += '\n';
    }

    if (outputFile) {
        await Deno.writeTextFile(outputFile, hdpgnContent);
        console.log(`HDPGN generated and saved to ${outputFile}`);
    } else {
        console.log(hdpgnContent);
    }
}

if (import.meta.main) {
    const replayFile = Deno.args[0];
    const outputFile = Deno.args[1];

    if (!replayFile) {
        console.error("Usage: deno run --allow-read --allow-write generate_hdpgn.ts <replay_file.json> [output_file.hdpgn]");
        Deno.exit(1);
    }

    generateHDPGN(replayFile, outputFile);
}